apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-deck
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-username>/kong-gitops
    targetRevision: HEAD
    path: deck-sync
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

