apiVersion: v1
kind: ConfigMap
metadata:
  name: deck-config
data:
  kong.yaml: |
    _format_version: "3.0"
    services:
    - connect_timeout: 60000
      enabled: true
      host: omdbapi.com
      name: test
      path: /
      port: 443
      protocol: https
      read_timeout: 60000
      retries: 5
      routes:
      - https_redirect_status_code: 426
        name: test
        path_handling: v0
        paths:
        - /api
        preserve_host: false
        protocols:
        - http
        - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
      write_timeout: 60000

