apiVersion: batch/v1
kind: Job
metadata:
  name: deck-sync
spec:
  template:
    spec:
      containers:
      - name: deck
        image: kong/deck:latest
        command:
          - /bin/sh
          - -c
          - |
            deck ping --kong-addr http://192.168.49.2:30791/ && \
            deck sync --state /config/kong.yaml --kong-addr http://192.168.49.2:30791/
        volumeMounts:
        - name: config
          mountPath: /config
      restartPolicy: Never
      volumes:
      - name: config
        configMap:
          name: deck-config
  backoffLimit: 3

